version: '3.1'

services:
  app:
    image: glen/gitlab-registry-cleanup-hook:latest
    env_file:
      - .env
    ports:
      - 8000:8000
    secrets:
      - gitlab-root-password
      - gitlab-hook-token
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

secrets:
  gitlab-root-password:
    external: true
  gitlab-hook-token:
    external: true

# vim:ts=2:sw=2:et
