version: '2'

services:
  app:
    build: .
    volumes:
      - $REGISTRY_BUCKET_PATH/docker/registry:/var/opt/gitlab/gitlab-rails/shared/registry/docker/registry:rw
    env_file:
      - .env
    ports:
      - 8000:8000
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

# vim:ts=2:sw=2:et
